#!/bin/bash

# Inspired from this blog article : http://www.thegeekstuff.com/2013/10/time-command-format/

BAR="[0m[7m [27m[0m"

if [ $# -eq 0 ]; then
  echo "Usage: $0 command <argv>..."
  echo ""
  exit 1
fi

FILE=$(mktemp)

time=$(command -v gtime || command -v /usr/bin/time)
grep=$(command -v ggrep || command -v /usr/bin/grep)

$time -o $FILE -f "       Total $BAR %es  [%P  %MK  %I/%O]" ets -s -f "%Mm  %S.%Ls $BAR" -- "$@"
code=$?

echo "             $BAR"
cat $FILE
exit $code
