[env]
NODE_ENV = 'production'
DENO_NO_PACKAGE_JSON=1
FORCE_COLOR=1
_.path = [ "./node_modules/.bin" ]


[tools]

[tasks.build]
run = 'echo "running build tasks"'

[tasks.jobs]
run = '''
  {{config_root}}/.cron/jobs/example1.job.ts
  {{config_root}}/.cron/jobs/example2.job.ts
  {{config_root}}/.cron/jobs/example3.job
  {{config_root}}/.cron/jobs/example4.job.ts
'''
