[env]
NODE_ENV = 'production'
DENO_NO_PACKAGE_JSON=1
FORCE_COLOR=1
_.path = [ "./node_modules/.bin" ]


[tools]

[tasks.build]
run = 'echo "running build tasks"'

[tasks.job1]
run = '{{config_root}}/.cron/jobs/example1.job.ts'

[tasks.job2]
run = '{{config_root}}/.cron/jobs/example2.job.ts'
