# eslint-disable yml/no-empty-mapping-value
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Enable debugging
        required: false
        default: false

  push:
    branches: [main]
  pull_request:

  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  # schedule:
  #   - cron: '5 4 * * *'

jobs:

  # Job  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  build:
    name: job ❯ build & run
    runs-on: ubuntu-22.04
    steps:
      # ─────────────────────────────────────────────────────
      - name: Github ❯ actions/checkout@v3
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # ─────────────────────────────────────────────────────
      - name: Github ❯ denoland/setup-deno@v1
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # ─────────────────────────────────────────────────────
      - name: Bootstrap ❯ Set env variables
        run: |
          .github/scripts/helpers set-env-variables

      # ─────────────────────────────────────────────────────
      - name: Bootstrap ❯ Preinstall & Prepare Environment
        run: |
          mkdir -p ~/.local/bin
          .github/scripts/helpers preinstall-binaries
          .github/scripts/helpers ___

          .github/scripts/helpers create-directories
          .github/scripts/helpers optimize-ubuntu
          .github/scripts/helpers show-system-information
          .github/scripts/helpers dump-env

          .github/scripts/deps

      # ─────────────────────────────────────────────────────
      - uses: actions/cache@v3
        name: Bootstrap ❯ Restore Cache
        with:
          path: ${{ env.ACTIONS_CACHE_DIR }}
          key:  ${{ runner.os }}-v1-store-${{ env.CACHE_PREFIX }}-${{ hashFiles('**/deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-v1-store-${{ env.CACHE_PREFIX }}-
            ${{ runner.os }}-v1-store-

      - uses: actions/cache@v3
        name: Bootstrap ❯ Restore TTL Cache
        with:
          path: ${{ env.TTL_CACHE_DIR }}
          key:  ${{ runner.os }}-ttl-cache-${{ github.head_ref }}


      # ─────────────────────────────────────────────────────
      - name: Cron ❯ Job1
        run: |
          echo
          echo "start $(date +%H:%M:%S)"
          bkt --ttl=60s -- sleep 3
          echo "stop $(date +%H:%M:%S)
          echo

          .github/scripts/pstats deno task job1

      # ─────────────────────────────────────────────────────
      - name: Post hooks ❯ Commit to repository
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . --verbose
          stats=$(git diff --cached --shortstat | sed -E 's/ (insertion|insertions|deletion|deletions)//g')
          git commit -m "⚡️ CI: $stats [skip ci]" -a || true
          git push

      # # ─────────────────────────────────────────────────────
      - name: "Debug: Context Information"
        id: github_context_step
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Public ip: $(curl -sS icanhazip.com)"
          uptime
          .github/scripts/helpers show-cache-folders
          .github/scripts/helpers show-cache-structure
          mkdir -p $DEBUG_DIR &> /dev/null
          .github/scripts/helpers ___

          echo '${{ toJSON(github) }}'    >> $DEBUG_DIR/github.json &
          echo '${{ toJSON(job) }}'       >> $DEBUG_DIR/job.json &
          echo '${{ toJSON(steps) }}'     >> $DEBUG_DIR/steps.json &
          echo '${{ toJSON(runner) }}'    >> $DEBUG_DIR/runner.json &
          echo '${{ toJSON(strategy) }}'  >> $DEBUG_DIR/strategy.json &
          echo '${{ toJSON(matrix) }}'    >> $DEBUG_DIR/matrix.json &
          wait

          .github/scripts/helpers dump-context
